export type ContentMode = 'uppercase' | 'lowercase' | 'numbers' | 'words' | 'sentences' | 'random' | 'custom';

const UPPERCASE = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('');
const LOWERCASE = 'abcdefghijklmnopqrstuvwxyz'.split('');
const NUMBERS = '0123456789'.split('');

const WORDS = [
  // 3-letter
  'the', 'cat', 'dog', 'sun', 'run', 'fly', 'and', 'but', 'for',
  'you', 'are', 'was', 'had', 'hot', 'cup', 'top', 'mix', 'box',
  'hat', 'bat', 'mat', 'sat', 'rat', 'map', 'cap', 'lap', 'tap',
  'big', 'pig', 'dig', 'fig', 'wig', 'lip', 'dip', 'tip',
  'fun', 'bun', 'gun', 'pun', 'log', 'fog', 'bog', 'cog',
  'web', 'bed', 'red', 'fed', 'led', 'pen', 'hen', 'ten', 'den',
  'jam', 'ham', 'yam', 'dam', 'ram', 'arm', 'jar', 'tar', 'bar',
  'hop', 'mop', 'pop', 'cop', 'sob', 'mob', 'job', 'rob',
  'ice', 'ace', 'age', 'ore', 'eve', 'axe', 'aye',
  'sky', 'dry', 'fry', 'cry', 'try', 'spy', 'shy',
  'oak', 'bay', 'cay', 'ray', 'say', 'pay', 'hay', 'day', 'way',
  'owl', 'elk', 'emu', 'gnu', 'yak', 'koi', 'asp',
  'arc', 'orb', 'hub', 'nub', 'cub', 'pub', 'rub', 'sub', 'tub',
  'zip', 'zap', 'zig', 'zen',
  // 4-letter
  'cake', 'lake', 'make', 'bake', 'fake', 'rake', 'take', 'wake',
  'bold', 'cold', 'fold', 'gold', 'hold', 'mold', 'sold', 'told',
  'bird', 'fire', 'fish', 'frog', 'gate', 'glow', 'good',
  'grip', 'grow', 'hair', 'hand', 'hard', 'harm', 'harp', 'heat',
  'heel', 'help', 'hero', 'high', 'hike', 'hill', 'hint', 'home',
  'hook', 'hope', 'horn', 'host', 'hunt', 'idea', 'inch',
  'iron', 'jade', 'jazz', 'jest', 'join', 'joke', 'jump', 'just',
  'keen', 'keep', 'kick', 'kind', 'king', 'kiss', 'kite', 'knot',
  'lamp', 'land', 'lark', 'last', 'leaf', 'lean', 'leap', 'left',
  'lend', 'lift', 'like', 'lime', 'link', 'lion', 'list', 'live',
  'lock', 'loft', 'loom', 'loop', 'lure', 'lush',
  'mane', 'mark', 'mast', 'meal', 'meet', 'melt', 'mesh',
  'mild', 'milk', 'mill', 'mind', 'mine', 'mint', 'mist', 'mode',
  'moon', 'moor', 'more', 'moss', 'move', 'much', 'muse', 'must',
  'nail', 'name', 'nest', 'next', 'nice', 'nine', 'node', 'noon',
  'norm', 'nose', 'note', 'noun', 'nova', 'nuts',
  'oath', 'odds', 'once', 'only', 'open', 'opus', 'oven',
  'over', 'pack', 'page', 'pain', 'pair', 'palm', 'park',
  'part', 'past', 'path', 'pave', 'peak', 'pear', 'peel', 'peer',
  'pick', 'pier', 'pike', 'pile', 'pine', 'pink', 'pipe', 'plan',
  'play', 'plot', 'plow', 'plum', 'plus', 'poem', 'poet', 'pole',
  'pond', 'pool', 'port', 'pose', 'post', 'pour', 'prey', 'prow',
  'pull', 'pure', 'push', 'quiz', 'race', 'rack', 'rage', 'rain',
  'rank', 'rare', 'read', 'real', 'reap', 'reef', 'reel', 'rely',
  'rent', 'rest', 'rice', 'rich', 'ride', 'ring', 'riot', 'rise',
  'risk', 'road', 'roam', 'roar', 'robe', 'rock', 'roll',
  'roof', 'room', 'rope', 'rose', 'ruby', 'ruin', 'rule', 'rush',
  'rust', 'safe', 'sage', 'sail', 'sake', 'salt', 'same', 'sand',
  'save', 'scan', 'scar', 'seal', 'seam',
  'seek', 'seem', 'self', 'sell', 'send', 'shed', 'shin',
  'ship', 'shoe', 'shop', 'shot', 'show', 'shut', 'side', 'sigh',
  'silk', 'sill', 'sing', 'sink', 'site', 'size', 'skin', 'skip',
  'slam', 'slap', 'slim', 'slip', 'slot', 'slow', 'slug',
  'snap', 'snow', 'soap', 'sock', 'soft', 'soil', 'song',
  'soon', 'sort', 'soul', 'soup', 'sour', 'span', 'spin', 'spot',
  'spur', 'star', 'stay', 'stem', 'step', 'stew', 'stir', 'stop',
  'such', 'suit', 'sung', 'sunk', 'sure', 'surf',
  'swan', 'swap', 'sway', 'swim', 'tale', 'tall', 'tame',
  'task', 'team', 'teal', 'tear', 'tell', 'term', 'test', 'text',
  'than', 'that', 'them', 'then', 'they', 'thin', 'this', 'tide',
  'tile', 'time', 'tiny', 'tire', 'toad', 'toll', 'tomb',
  'tone', 'tool', 'torn', 'toss', 'tour', 'town', 'trap',
  'tree', 'trek', 'trim', 'trio', 'trip', 'true', 'tuck',
  'tuna', 'tune', 'turf', 'turn', 'tusk', 'twig', 'type',
  'undo', 'unit', 'upon', 'vane', 'vary',
  'vast', 'veil', 'vein', 'very', 'vest', 'view', 'vine',
  'volt', 'vote', 'wade', 'wage', 'walk', 'wall', 'wand',
  'ward', 'warm', 'warp', 'wash', 'wasp', 'wave', 'ways',
  'weak', 'wear', 'weed', 'week', 'weld', 'well',
  'whip', 'wide', 'wild', 'will', 'wind', 'wine',
  'wing', 'wink', 'wire', 'wise', 'wish', 'wolf',
  'wood', 'wool', 'word', 'worm', 'wrap', 'wren',
  'yarn', 'yell', 'yolk', 'zero', 'zest', 'zinc',
  'zone', 'zoom', 'blur', 'buzz', 'fizz', 'gust', 'haze',
  'lace', 'mace', 'pace', 'race', 'vase', 'laze', 'gaze', 'maze',
  'dusk', 'husk', 'musk', 'rusk', 'tusk',
  'daze', 'faze', 'raze', 'glee', 'flee', 'free', 'tree',
  // 5-letter
  'about', 'above', 'acute', 'admit', 'adore', 'adult', 'after',
  'again', 'agile', 'alarm', 'album', 'alert', 'alien', 'align',
  'alive', 'aloft', 'alone', 'along', 'aloud', 'alpha', 'alter',
  'amber', 'angel', 'angry', 'anime', 'ankle', 'annex', 'antic',
  'anvil', 'apart', 'apple', 'apply', 'apron', 'array', 'arrow',
  'atlas', 'attic', 'audio', 'audit', 'avail', 'avoid', 'awake',
  'award', 'aware', 'awful', 'badly', 'bagel', 'basic', 'basis',
  'beach', 'beard', 'beast', 'began', 'begin', 'being', 'below',
  'bench', 'berry', 'bevel', 'birch', 'black', 'blade', 'blame',
  'bland', 'blank', 'blast', 'blaze', 'bleak', 'bleed', 'blend',
  'bless', 'blind', 'bliss', 'block', 'bloom', 'blown', 'blues',
  'blunt', 'board', 'bonus', 'boost', 'booth', 'braid',
  'brain', 'brave', 'bread', 'break', 'breed', 'brick',
  'bride', 'brief', 'brine', 'bring', 'brisk', 'broad', 'broke',
  'brook', 'brown', 'brush', 'budge', 'build', 'built', 'bulge',
  'burst', 'cabin', 'camel', 'candy', 'carry', 'catch', 'cause',
  'cedar', 'chair', 'chalk', 'charm', 'chart', 'chase', 'cheap',
  'check', 'cheer', 'chess', 'chest', 'chief', 'child', 'chill',
  'chimp', 'chips', 'choir', 'civic', 'civil', 'claim', 'clamp',
  'clash', 'clasp', 'class', 'clean', 'clear', 'clerk', 'click',
  'cliff', 'climb', 'cling', 'clock', 'clone', 'close', 'cloth',
  'cloud', 'coach', 'coast', 'cobra', 'comet', 'comic',
  'coral', 'could', 'count', 'court', 'cover', 'craft', 'crane',
  'crash', 'crazy', 'cream', 'creek', 'crisp', 'cross', 'crowd',
  'crown', 'cruel', 'crush', 'curve', 'cycle', 'daily', 'dance',
  'datum', 'daunt', 'dazed', 'decay', 'decoy', 'delve',
  'dense', 'depth', 'derby', 'digit', 'disco', 'dizzy',
  'dodge', 'doubt', 'dough', 'draft', 'drain',
  'drape', 'drawl', 'dream', 'dress', 'dried', 'drift',
  'drill', 'drink', 'drive', 'drone', 'drown', 'drums',
  'dusty', 'dwarf', 'dwell',
  'eager', 'early', 'earth', 'eight', 'elect', 'elite',
  'email', 'ember', 'empty', 'enjoy', 'enter', 'entry',
  'equal', 'error', 'essay', 'event', 'every',
  'exact', 'exist', 'extra', 'fable', 'facet', 'faint', 'faith',
  'false', 'fancy', 'feral', 'fetch', 'fever', 'fiber', 'field',
  'fifth', 'fifty', 'fight', 'final', 'first', 'fixed', 'fjord',
  'flame', 'flare', 'flash', 'flask', 'fleet', 'flesh', 'float',
  'flock', 'flood', 'floor', 'flour', 'flute', 'focus', 'force',
  'forge', 'forth', 'forum', 'found',
  'frame', 'frank', 'fraud', 'fresh', 'front', 'frost', 'froze',
  'fruit', 'fully', 'funny', 'gauge', 'giant', 'given',
  'gland', 'glare', 'glass', 'glide', 'gloom', 'gloss', 'glove',
  'going', 'grace', 'grade', 'graft', 'grain', 'grand', 'grant',
  'grape', 'grasp', 'grass', 'grate', 'grave', 'graze', 'great',
  'greed', 'green', 'greet', 'grief', 'grind', 'groan',
  'gross', 'group', 'grove', 'growl', 'grown',
  'guard', 'guava', 'guile', 'gusto',
  'harsh', 'haven', 'hazel', 'heart', 'heavy', 'hedge', 'helix',
  'hence', 'herbs', 'hinge', 'hippo', 'hoist', 'holly', 'honey',
  'honor', 'horse', 'hotel', 'house', 'hound', 'human', 'humid',
  'humor', 'hurry', 'hyena', 'image', 'imply', 'infer', 'ingot',
  'intro', 'issue', 'ivory', 'jaunt', 'jetty', 'jewel',
  'jolly', 'judge', 'juice', 'juicy', 'jumpy', 'kayak',
  'knack', 'kneel', 'knife', 'knock', 'known', 'koala', 'label',
  'lance', 'large', 'laser', 'later', 'lathe', 'laugh', 'layer',
  'learn', 'lease', 'ledge', 'legal', 'lemon', 'level', 'light',
  'linen', 'liver', 'llama', 'lodge', 'logic', 'loose', 'lover',
  'lower', 'loyal', 'lucky', 'lunar', 'lyric', 'magic',
  'major', 'maker', 'manga', 'manor', 'maple', 'march', 'match',
  'matte', 'maxim', 'mayor', 'media', 'mercy', 'merit', 'merry',
  'metal', 'mimic', 'minor', 'minus', 'mixed', 'model', 'mogul',
  'money', 'month', 'moral', 'moose', 'mossy', 'motif', 'motor',
  'motto', 'mount', 'mouse', 'mouth', 'murky', 'music',
  'naive', 'nerve', 'night', 'ninja', 'noble',
  'noise', 'nymph', 'ocean', 'olive', 'onset', 'orbit', 'order',
  'other', 'outer', 'outdo', 'owned', 'oxide', 'ozone',
  'paint', 'panel', 'panic', 'paper', 'patch', 'pause', 'peace',
  'pedal', 'penny', 'perch', 'peril', 'petal', 'petty', 'phase',
  'phone', 'photo', 'piano', 'piece', 'pilot', 'pinch', 'pixel',
  'pizza', 'place', 'plaid', 'plain', 'plane', 'plant', 'plate',
  'plaza', 'plead', 'pluck', 'plume', 'plush', 'point', 'polar',
  'poppy', 'porch', 'posed', 'power',
  'press', 'price', 'pride', 'prime', 'print', 'prior', 'prize',
  'probe', 'prone', 'proof', 'prose', 'proud', 'prove',
  'pulse', 'pupil', 'purse', 'queen', 'query',
  'quest', 'queue', 'quick', 'quiet', 'quota', 'quote',
  'radar', 'rally', 'ranch', 'range', 'rapid', 'ratio',
  'raven', 'reach', 'ready', 'realm', 'rebel', 'refer',
  'reign', 'relax', 'resin', 'retro',
  'revel', 'rigid', 'risky', 'rivet', 'robot', 'rocky',
  'rogue', 'roost', 'rough', 'round', 'route',
  'royal', 'rugby', 'ruler', 'rumor', 'rusty',
  'salad', 'sauce', 'scale', 'scene', 'scent', 'scone',
  'scope', 'score', 'scout', 'screw', 'scrub', 'seize', 'sense',
  'serve', 'seven', 'shard', 'share', 'shark', 'sharp', 'shawl',
  'sheep', 'sheer', 'shelf', 'shell', 'shift', 'shiny', 'shirt',
  'shock', 'shore', 'short', 'shout', 'shrug', 'sight',
  'since', 'siren', 'skill', 'skirt', 'skull', 'slate',
  'sleet', 'slick', 'slide', 'slope', 'sloth', 'small',
  'smart', 'smash', 'smell', 'smile', 'smirk', 'smoke', 'snack',
  'snake', 'snare', 'sneak', 'sniff', 'solar', 'solid', 'solve',
  'space', 'spare', 'spark', 'spawn', 'speak', 'spear', 'speck',
  'speed', 'spell', 'spend', 'spice', 'spill', 'spine', 'spite',
  'spoke', 'spook', 'spoon', 'spore', 'sport', 'spout',
  'squad', 'squat', 'squid', 'stack', 'staff', 'stage',
  'stain', 'stake', 'stale', 'stall', 'stamp', 'stand', 'stark',
  'state', 'steam', 'steel', 'steep', 'steer',
  'stern', 'stick', 'stiff', 'still', 'sting', 'stock', 'stoic',
  'stone', 'store', 'storm', 'story', 'stout', 'strap',
  'straw', 'stray', 'strip', 'stuck', 'study',
  'stump', 'stunt', 'style', 'sugar', 'sunny',
  'super', 'surge', 'swamp', 'swear', 'sweat', 'sweep', 'sweet',
  'swift', 'swipe', 'swoop', 'sword',
  'syrup', 'talon', 'tango', 'taunt',
  'tempt', 'tense', 'their', 'theme', 'there',
  'these', 'thick', 'thing', 'think', 'third', 'thorn', 'those',
  'three', 'throw', 'thumb', 'thump', 'tiger', 'tight',
  'timer', 'titan', 'title', 'toast', 'today', 'token',
  'torch', 'total', 'touch', 'tough', 'towel', 'tower', 'toxic',
  'trace', 'track', 'trade', 'trail', 'train', 'trait',
  'trash', 'trend', 'trick', 'troop', 'trout',
  'trove', 'truce', 'truck', 'truly', 'trunk',
  'trust', 'truth', 'tulip', 'tutor',
  'twirl', 'twist', 'ultra', 'uncle', 'unify', 'union', 'until',
  'upper', 'upset', 'urban', 'usher', 'utter', 'vague', 'valid',
  'valor', 'value', 'valve', 'vault', 'video',
  'vigil', 'vigor', 'viral', 'virus', 'visor', 'vista', 'vital',
  'vivid', 'vocal', 'vogue', 'voice', 'vouch',
  'waltz', 'watch', 'water', 'weave', 'wedge', 'weigh', 'weird',
  'whale', 'wheat', 'wheel', 'where', 'which', 'while', 'white',
  'whole', 'whose', 'wider', 'witch', 'witty', 'woman',
  'women', 'world', 'worry', 'worse', 'worst', 'worth', 'would',
  'wound', 'wrath', 'wreck', 'wring', 'wrist', 'write', 'wrote',
  'yacht', 'yearn', 'yield', 'young', 'yours', 'youth', 'zebra',
  // 6-letter bonus
  'bronze', 'castle', 'coffee', 'breeze', 'candle', 'carpet',
  'circle', 'cloudy', 'coyote', 'crayon', 'dagger', 'donkey',
  'fabric', 'falcon', 'frenzy', 'frozen', 'garden', 'garlic',
  'goblin', 'gravel', 'harbor', 'helmet', 'hollow', 'insect',
  'jigsaw', 'jungle', 'kernel', 'kitten', 'knight', 'lantern',
  'lavish', 'legend', 'lizard', 'marble', 'mirror', 'mitten',
  'monkey', 'mother', 'muffin', 'musket', 'noodle', 'normal',
  'orange', 'orchid', 'oyster', 'parrot', 'pebble', 'pencil',
  'pepper', 'pickle', 'planet', 'pocket', 'ponder', 'portal',
  'potion', 'powder', 'puzzle', 'python', 'rabbit', 'radish',
  'rattle', 'rescue', 'riddle', 'ripple', 'rocket', 'rustle',
  'salmon', 'sandal', 'saturn', 'savage', 'scorch', 'scroll',
  'season', 'secret', 'silver', 'simple', 'sketch', 'sleepy',
  'social', 'socket', 'spider', 'spiral', 'splash', 'sprout',
  'squash', 'statue', 'steady', 'stream', 'stride', 'string',
  'stroke', 'sunset', 'switch', 'symbol', 'tandem', 'target',
  'temple', 'tender', 'timber', 'toggle', 'tomato', 'tongue',
  'topher', 'toucan', 'travel', 'trowel', 'tunnel', 'turtle',
  'tuxedo', 'typhon', 'unique', 'vacuum', 'valley', 'velvet',
  'vessel', 'viking', 'violet', 'violin', 'vision', 'walrus',
  'walnut', 'wander', 'warden', 'warmth', 'whisky', 'wicker',
  'willow', 'window', 'winner', 'wisdom', 'wombat', 'wonder',
  'wooden', 'yogurt', 'zipper',
];

const SENTENCES = [
  // Very short (2–3 words)
  'just breathe',
  'keep going',
  'be bold',
  'stay sharp',
  'try harder',
  'move fast',
  'look up',
  'stay cool',
  'well done',
  'dig deep',
  'be kind',
  'aim high',
  'go again',
  'stay wild',
  'nice work',
  'push through',
  'feel it',
  'hold still',
  'stand tall',
  'slow down',
  'eyes open',
  'stay true',
  'do it',
  'live well',
  'think big',
  'be brave',
  'stay calm',
  'chase it',
  'make waves',
  'never quit',
  // Short (4–5 words)
  'light the fire now',
  'catch me if you can',
  'run to the hills',
  'look before you leap',
  'over the moon now',
  'fly high and far',
  'hold the line here',
  'find a way through',
  'read between the lines',
  'rise and then shine',
  'bite the bullet hard',
  'turn the page now',
  'follow your own path',
  'watch the world go',
  'hear the ocean roar',
  'feel the cool breeze',
  'taste the morning air',
  'trust the quiet voice',
  'the fog will lift',
  'let the light in',
  'time heals most things',
  'take the leap now',
  'break the old mold',
  'draw your own map',
  'the stars are out',
  'make the most of it',
  'write it all down',
  'say yes more often',
  'dance in the rain',
  'find the silver lining',
  // Nature & weather
  'the cat sat on a mat',
  'rain drums on the tin roof',
  'frost on the morning grass',
  'the tall oak bends in wind',
  'snow fell through the night',
  'soft light fills the room',
  'a big red fox jumps',
  'fly high into the clouds',
  'the dog ran far away',
  'the sun is very bright',
  'the bird sang at dawn',
  'the fish swam upstream',
  'leaves fall like gold coins',
  'chase the last rays of sun',
  'stars burn like tiny fires',
  'the moon hangs low and full',
  'waves crash on the rocky shore',
  'fog rolls in off the water',
  'the forest is deep and green',
  'a lone hawk circles overhead',
  'ice forms on the quiet pond',
  'the creek runs fast after rain',
  'cold air bites at your cheeks',
  'the sky turns pink at dusk',
  'bees hum in the clover field',
  // Action & movement
  'climb to the top of the hill',
  'toss the stone far out to sea',
  'paddle hard up the current',
  'stretch up and touch the shelf',
  'jump over the old stone wall',
  'run through the open field',
  'catch the wave as it breaks',
  'spin until the world blurs',
  'leap from rock to rock',
  'sprint to the end of the lane',
  'roll down the grassy slope',
  'dive deep beneath the surface',
  'slide across the frozen lake',
  'swing high above the treetops',
  'march in step with the drum',
  'dash across the finish line',
  'stretch up to reach the shelf',
  'skip flat stones on water',
  // Food & drink
  'pick ripe berries in the sun',
  'squeeze lemons into cold water',
  'knead the dough until smooth',
  'pour the milk slow and steady',
  'fold the omelette carefully',
  'drink some hot peppermint tea',
  'bake an apple pie from scratch',
  'stir the soup until it steams',
  'slice the bread while warm',
  'boil the kettle for tea',
  'fry the eggs in butter',
  'melt dark chocolate in a bowl',
  'grill corn over an open flame',
  'mix flour and sugar with care',
  'chop garlic on the board',
  // Creative & art
  'stitch the cloth with care',
  'play the old piano softly',
  'print the words in neat lines',
  'read a worn book by lamplight',
  'draw a big bright yellow star',
  'write your name in the sand',
  'sketch the face from memory',
  'carve letters into soft clay',
  'fold paper into a tiny crane',
  'hum a tune nobody else knows',
  'sculpt a figure from wet clay',
  'weave patterns into the basket',
  // Moods & feelings
  'goosebumps when the beat drops',
  'still and calm as quiet water',
  'dizzy with nerves and wonder',
  'keep it calm and carry on',
  'feel the rhythm in your chest',
  'breathe in and let it go',
  'the quiet before a big moment',
  'a sudden burst of pure joy',
  'the warmth of a long hug',
  'proud of every small step',
  'curious about what comes next',
  // Everyday life
  'fold the laundry into piles',
  'fix the loose tile on the step',
  'wipe the table after each meal',
  'leave a note by the front door',
  'lock the door on your way out',
  'feed the dog before you leave',
  'water the plants on the ledge',
  'make the bed in the morning',
  'find the keys under the couch',
  'charge the phone before bed',
  'take the bin out on Tuesday',
  'pack the bag the night before',
  'set the alarm for six am',
  'sort the mail into piles',
  'sweep the porch of dry leaves',
  // Adventure & exploration
  'follow the trail through pines',
  'ford the stream at the bend',
  'mark your route on the chart',
  'the summit is close now',
  'the desert glows at dusk',
  'sleep under a canopy of stars',
  'break camp before sunrise',
  'pitch the tent on level ground',
  'read the map by torchlight',
  'a hidden cove behind the cliff',
  'find shelter before the storm',
  // Playful & whimsical
  'she sells seashells by the sea',
  'sing your heart out in the car',
  'a bear who bakes fresh bread',
  'ghosts humming in the hallway',
  'teach the parrot to do taxes',
  'write a note to future you',
  'a warm cup of tea fixes things',
  'the quick brown fox leaps high',
  'over the moon and back again',
  'count to ten and then let go',
  'dance like nobody is watching',
  'wear the silly hat with pride',
  'eat breakfast food for dinner',
  'penguins in a very long queue',
  'the robot learned to waltz',
  'a dragon who loves crosswords',
  'the snail won on a loophole',
  'invent a new word each Tuesday',
  // Vivid images
  'gold and copper leaves in fall',
  'old cobblestones wet from rain',
  'rows of lavender in still air',
  'the last page of a great book',
  'the smell of rain on dry earth',
  'lanterns float into the dark',
  'neon sign flickers in the rain',
  'a city that never fully sleeps',
  'salt and woodsmoke on cool air',
  'the lighthouse sweeps the fog',
  'embers glow past midnight',
  'confetti caught in the updraft',
  'a polaroid developing slowly',
  'the creak of an old swing set',
  'dust motes in a beam of light',
  // Motivational & reflective
  'break the record by one second',
  'best view is after the climb',
  'be what you needed back then',
  'fear is excitement with brakes',
  'build the habit not the mood',
  'trust the process in the fog',
  'small steps still move forward',
  'try again with what you know',
  'start before you feel ready',
  'rest is part of the work',
  'done is better than perfect',
  'you already know what to do',
  'keep going past the hard part',
  'one good day follows another',
];

const CATEGORIES = [UPPERCASE, LOWERCASE, NUMBERS, WORDS, SENTENCES];

const POOL: Record<Exclude<ContentMode, 'random' | 'custom'>, string[]> = {
  uppercase: UPPERCASE,
  lowercase: LOWERCASE,
  numbers: NUMBERS,
  words: WORDS,
  sentences: SENTENCES,
};

export function getTarget(mode: ContentMode, exclude?: string, rng: () => number = Math.random): string {
  if (mode === 'random') {
    const category = CATEGORIES[Math.floor(rng() * CATEGORIES.length)];
    const filtered = exclude ? category.filter((t) => t !== exclude) : category;
    const pool = filtered.length > 0 ? filtered : category;
    return pool[Math.floor(rng() * pool.length)];
  }
  if (mode === 'custom') return '';
  const pool = POOL[mode];
  const filtered = exclude ? pool.filter((t) => t !== exclude) : pool;
  const safe = filtered.length > 0 ? filtered : pool;
  return safe[Math.floor(rng() * safe.length)];
}

export function getFontSize(target: string, canvasH: number): number {
  const base = Math.min(canvasH * 0.38, 200);
  // Gentle scaling — the size picker is the primary control, not character count
  if (target.length === 1) return base;
  if (target.length <= 4) return base * 0.9;
  if (target.length <= 10) return base * 0.8;
  return base * 0.72; // sentences word-wrap, so don't shrink much
}
